name: DangerJS Notification
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .github/actions/dangerjs

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run danger
        uses: ./.github/actions/dangerjs
        with:
          dangerfile: .github/danger/dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
