name: DangerJS Notification
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Danger
        uses: danger/danger-js@9.1.6
        with:
          args: "--dangerfile dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

