name: DangerJS Notification
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout actions library
        uses: actions/checkout@v2
        with:
          repository: DragosDumitrache/actions-library
          token: ${{ secrets.GH_TOKEN }}
          path: .private-actions/

      - name: Run danger
        uses: ./.private-actions/dangerjs
