name: DangerJS Notification
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Salut"
        uses: dragosdumitrache/actions-library/greetings@main
      - name: "Hipster"
        uses: dragosdumitrache/actions-library/wazzap@main
