name: DangerJS Notification
on:
  pull_request:
  workflow_dispatch:
    inputs:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check changes to topic atlantis.yaml
        id: check_atlantis
        run: |
          # Use github.event.before, which should represent the SHA of the
          # previous commit on master, as the ref to diff against.
          # This should do the right thing in the case of merge commits.
          if [ -z "$(git diff-tree --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} **/atlantis.yaml)" ]; then
            echo "Atlantis yaml $1 unchanged"
            exit 0
          fi

          echo "atlantis_changed=changed" >> $GITHUB_OUTPUT
      - name: Check changes to any TF
        id: check_tf
        run: |
          # Use github.event.before, which should represent the SHA of the
          # previous commit on master, as the ref to diff against.
          # This should do the right thing in the case of merge commits.
          if [ -z "$(git diff-tree --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} **/*.tf)" ] || [ -z "$(git diff-tree --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} **/*.tfvalues)" ]; then
            echo "terraform unchanged"
            exit 0
          fi

          echo "tf_changed=changed" >> $GITHUB_OUTPUT

      - name: Print output
        if: steps.check_atlantis.outputs.atlantis_changed == 'changed' && steps.check_tf.outputs.tf_changed == 'changed'
        run: |
          echo "Changes to `atlantis.yaml` have to be done independently from changes to any terraform files"
          exit 1
