name: Release new version

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Versioner
        id: versioner
        #        if: ${{ github.ref == 'refs/heads/master' }}
        uses: DragosDumitrache/versioner/versioner@2.2.2
      - name: Publish tag
        #        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.email robot@omnipresent.com
          git config --global user.name "GHA Robot"

          git branch --show-current

          echo ${{ steps.versioner.outputs.version }}
#          git tag -a ${{ steps.versioner.outputs.version }} -m ${{ steps.versioner.outputs.version }}
#          git push --tags
